name: Tag Release CI

# on:
#   push:
#     branches:
#       - master
#       - uat
#   pull_request:
#     branches:
#       - master

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target environment'
        required: true
        default: 'production'

jobs:
  build:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Check if tag exists in uat or prod
        env:
          target: '${{ github.event.inputs.target }}'
        run: |
          case "$target" in
            prod|uat)
              echo "This is $target branch"
              # Check if tag exists
              tag=$GITHUB_REF
              echo $tag
              ;;
            *)
              echo "Branch name: $target, do not need tag. Continue ..."
              ;;
          esac