name: Tag Release CI

# on:
#   push:
#     branches:
#       - master
#       - uat
#   pull_request:
#     branches:
#       - master

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target environment'
        required: true
        default: 'production'

jobs:
  build:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Tagging
        id: tagging
        uses: michalzegar/actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Output
        run: echo ${{ steps.tagging.outputs.tag_new }}
        